// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzltrqilxchclzjybzko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6bHRycWlseGNoY2x6anliemtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3Mzc4NjcsImV4cCI6MjA3MzMxMzg2N30.UFbwHW6V1qMr9amvA8NM20ZSK-u2O-Lh4DJbvbNebdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});